name = Base
description = A simple 2 column layout demonstrating mobile first and Susy.
preview = preview.png
template = base-layout

; Stylesheets
  stylesheets[all][] = fonts/fonts.css

; ========================================
; Scripts
; ========================================
  scripts[] = js/jquery.bpopup.min.js
  scripts[] = js/base-omega.behaviors.js
  scripts[] = js/init.js

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

